
CREATE TABLE IF NOT EXISTS `gb_user-analytics`(
	`day` INT UNSIGNED,
	`views` MEDIUMINT(6) UNSIGNED DEFAULT 1, 
	`reviews` MEDIUMINT(6) UNSIGNED DEFAULT 1, 
	PRIMARY KEY(`day`)
)ENGINE=InnoDB COMMENT='analytics';

CREATE TABLE IF NOT EXISTS `gb_pages`(
	`PageID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`views` MEDIUMINT(6) UNSIGNED DEFAULT 0,
	`time` INT UNSIGNED DEFAULT 0,
	`shares` MEDIUMINT(6) UNSIGNED DEFAULT 0,
	`comments` MEDIUMINT(6) UNSIGNED DEFAULT 0,
	`created` INT UNSIGNED NOT NULL DEFAULT 1,
	INDEX `time`(`created`),
	PRIMARY KEY(`PageID`)
)ENGINE=InnoDB COMMENT='analytics';